//
// Pet.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct Pet: Codable {

    public enum Status: String, Codable { 
        case available = "available"
        case pending = "pending"
        case sold = "sold"
    }

    public var _id: Int64?

    public var category: Category?

    public var name: String

    public var photoUrls: [String]

    public var tags: [Tag]?
    /** pet status in the store */
    public var status: Status?
    public init(_id: Int64? = nil, category: Category? = nil, name: String, photoUrls: [String], tags: [Tag]? = nil, status: Status? = nil) { 
        self._id = _id
        self.category = category
        self.name = name
        self.photoUrls = photoUrls
        self.tags = tags
        self.status = status
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case category
        case name
        case photoUrls
        case tags
        case status
    }

}
